language:

    - node_js

node_js:

    - stable

install:

    # install project before travis ci build
    - bash travis/install.sh

script:

    # travis ci build
    - bash travis/build.sh

after_success:

    # travis ci deploy after successful build
    - bash travis/deploy.sh
